export default {
  preset: 'ts-jest/presets/default-esm',
  extensionsToTreatAsEsm: ['.ts'],
  testEnvironment: 'node',
  moduleNameMapper: {
    '^../../src/tools/toolRegistry$': '<rootDir>/__mocks__/src/tools/toolRegistry.js',
    '^../../../src/tools/toolRegistry$': '<rootDir>/__mocks__/src/tools/toolRegistry.js',
    '^../../src/core/utils/logger$': '<rootDir>/__mocks__/src/core/utils/logger.js',
    '^../../../src/core/utils/logger$': '<rootDir>/__mocks__/src/core/utils/logger.js',
    '^../../src/mcp/adapters/localCliToolAdapter$': '<rootDir>/__mocks__/src/mcp/adapters/local-cli-tool-adapter.js',
    '^../../../src/mcp/adapters/localCliToolAdapter$': '<rootDir>/__mocks__/src/mcp/adapters/local-cli-tool-adapter.js',
    '^../../src/mcp/transports/stdioTransport$': '<rootDir>/__mocks__/src/mcp/transports/stdio-transport.js',
    '^../../../src/mcp/transports/stdioTransport$': '<rootDir>/__mocks__/src/mcp/transports/stdio-transport.js',
    '^../../src/mcp/transports/httpTransport$': '<rootDir>/__mocks__/src/mcp/transports/http-transport.js',
    '^../../../src/mcp/transports/httpTransport$': '<rootDir>/__mocks__/src/mcp/transports/http-transport.js',
    '^../../src/mcp/mcpServer$': '<rootDir>/__mocks__/src/mcp/mcp-server.js',
    '^../../../src/mcp/mcpServer$': '<rootDir>/__mocks__/src/mcp/mcp-server.js',
    '^../../src/context/filePathProcessor$': '<rootDir>/__mocks__/src/context/file-path-processor.js',
    '^../../../src/context/filePathProcessor$': '<rootDir>/__mocks__/src/context/file-path-processor.js',
    '^../../src/tools/localCliTool$': '<rootDir>/__mocks__/src/tools/local-cli-tool.js',
    '^../../../src/tools/localCliTool$': '<rootDir>/__mocks__/src/tools/local-cli-tool.js',
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@/(.*)$': '<rootDir>/src/$1',
    '^(\\.{1,2}/.*)\\.js$': '$1',
    '^../../src/tools/toolRegistry$': '<rootDir>/__mocks__/src/tools/tool-registry.js',
    '^../../src/core/config/configManager$': '<rootDir>/__mocks__/src/core/config/config-manager.js',
    '^../../src/providers/openai/openaiProvider$': '<rootDir>/__mocks__/src/providers/openai/openai-provider.js',
    '^../../src/providers/anthropic/anthropicProvider$': '<rootDir>/__mocks__/src/providers/anthropic/anthropic-provider.js',
    '^../../src/tools/toolExecutor$': '<rootDir>/__mocks__/src/tools/tool-executor.js',
  },
  transform: {
    '^.+\\.m?[tj]sx?$': [
      'ts-jest',
      {
        useESM: true,
      },
    ],
  },
  testMatch: ['**/tests/**/*.test.ts', '**/tests/**/*.spec.ts'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'mjs', 'jsx', 'json', 'node'],
  transformIgnorePatterns: [
    '/node_modules/(?!(env-paths|keytar))/', 
    '\\.pnp\\.[^\\/]+$'
  ],
  setupFilesAfterEnv: ['./tests/jest.setup.ts'],
};
